FRONTENDSCHOOL5/final-01-focal

src/components/Button/Button.jsx

공통 컴포넌트로 사용할 기본 버튼 UI 구현 반영
- className에 따라 네 가지 크기의 기본 버튼을 사용할 수 있게 구현
- active, disabled 여부에 따라 버튼 디자인 및 타입이 달라지도록 구현

[Common] 기본 버튼 UI 구현

---

src/pages/ProfileEditPage.jsx
src/routes/Router.jsx

프로필 정보 수정 페이지 UI 구현
- 공통 컴포넌트인 Header와, 기존에 회원가입 페이지에서 만들었던 ProfileInputContainer를 재사용하여
프로필 정보 수정 페이지 UI를 구현했습니다.
- Router코드에 프로필 정보수정 경로가 빠져있어서 추가했습니다.

[Profile] ProfileEditPage UI구현

---

src/components/Input/TextInput.jsx

TextInput Placeholder 스타일링
- TextInput Placeholder 스타일링 하는 것을 빼먹어서 CSS추가했습니다.

[Common] TextInput Placeholder 스타일 추가

---

src/Globalstyled.jsx
src/components/Input/TextInputBox.jsx

댓글/채팅창 입력 UI 구현 반영
- 댓글 및 채팅창 공통 UI 작업
- 이미지 선택 레이블 cursor: pointer 적용
- 입력 시 버튼 활성화되도록 구현
이미지 업로드 하는 페이지가 여러 군데 있어 추후 ImageUploader로 이미지 파일 input 기능을 재사용할 수 있도록 리팩토링 할 계획입니다.

[Common] 댓글/채팅 입력창 UI 구현

---

src/components/Modal/AlertModal.jsx

- 모달 UI 구현
- 경고 모달 UI 구현
- 모달이 뜨는 버튼이 아직 없어 홈페이지에서 보이는 것과 모달의 배경 색은 임시로 넣어 두었습니다.

[Modal] Alert Modal UI 구현

---

src/components/Post/PostReply.jsx
src/components/Post/PostUpload.jsx

PostUpload.jsx
PostReply.jsx
UI구현
PostUpload.jsx 게시글작성 UI
PostReply.jsx 게시글 댓글 컴포넌트 UI
PostUpload.jsx
PostReply.jsx

[Post]post UI구현

---

src/App.js
src/api/instance/authInstance.js
src/api/instance/baseInstance.js
src/components/Login/LoginForm.jsx
src/components/SignUp/ProfileForm.jsx
src/components/SignUp/SignUpForm.jsx
src/pages/ProfileEditPage.jsx
src/pages/SignUpPage.jsx
src/routes/Router.jsx
src/states/LoginState.js

로그인 기능 구현
- (axios instance 폴더 구조 변경)
- 로그인 api 요청 코드 작성
- (recoil 사용하기 위해 리코일 셋팅)
-  recoil 전역상태와 localstorage를 이용하여 로그인 후에도 로그인 상태를 유지 시킬 수 있도록 하기

[Login] 로그인 기능 구현

---

src/Globalstyled.jsx
src/assets/icons/delete.svg
src/components/Header/Header.jsx
src/components/Login/LoginForm.jsx
src/components/Post/PostUpload.jsx
src/pages/PostEditPage.jsx
src/pages/PostUploadPage.jsx
src/routes/Router.jsx

글 업로드, 수정 페이지 기능 구현
- 전체적인 UI 리팩토링(스크롤바 위치 수정 및 textarea 크기 자동 조절, 사진 컨테이너 CSS 스타일링)
- 글 업로드 페이지와 글 수정 페이지에서 같은 PostUpload 컴포넌트를 쓰기 때문에 재활용할 수 있도록 props 추가 할당
- 글 업로드와 글 수정 기능 구현
- 글 업로드
- 글 수정

[Post] 글 업로드, 수정 페이지 기능 구현

---

src/components/Post/PostCard.jsx
src/pages/HomePage.jsx

홈 화면 피드 기능 구현 반영
- 피드에 팔로우한 사용자 게시글 불러오기
- 없을 경우 유저 팔로우를 위한 검색하기 버튼 띄우기 (+로고 변경)
- 통신한 데이터 받아와 게시글(PostCard)에 정보 알맞게 들어가도록 구현
- PostCard 글, 이미지, 댓글 부분 클릭 시 상세 페이지로 이동하도록 구현
- 게시글 좋아요 기능 구현
이미지가 여러 장일 경우 처리는 추후 구현하겠습니다.
현재는 이미지가 없는 게시글도 있지만 게시글 업로드 시 이미지 추가가 필수로 이루어지도록 수정하여 향후에는 이미지 있는 게시글만 올라올 예정입니다.

[Feed] 홈 화면 피드 기능 구현

---

src/components/Header/Header.jsx
src/components/Input/TextInput.jsx
src/components/Product/ImageUpload.jsx
src/components/Product/ProductUpload.jsx
src/pages/ProductUploadPage.jsx

1. 이미지 업로드  컴포넌트 프리뷰 onChange prop 및 기능 추가
2. 상품 업로드 API 통신 구현
3. 유효성 검사 로직 추가
4. 상품 업로드 기능 구현
https://github.com/FRONTENDSCHOOL5/final-01-focal/assets/117337499/f1118a1d-fb17-413d-97b4-877f7ddfe860

[Product] 상품 업로드 기능 구현

---

src/components/Button/Button.jsx
src/components/Profile/MyInfoBtns.jsx
src/components/Profile/ProductItem.jsx
src/components/Profile/ProfileInfo.jsx
src/components/Profile/ProfilePosts.jsx
src/components/Profile/ProfileProducts.jsx
src/components/Profile/UserInfoBtns.jsx
src/pages/MyProfilePage.jsx
src/pages/UserProfilePage.jsx

- 프로필 정보 가져오기
- 상품 목록 가져오기
- 팔로우
- 프로필 정보 가져오기
- 상품목록 가져오기
- 유저프로필 팔로우 언팔로우
- 링크 연결
- 프로필 피드는 갯수까지만 반영, pull 받고 다시 작업 예정
https://github.com/FRONTENDSCHOOL5/final-01-focal/assets/78803088/72f28fb5-21e5-4d1e-94f3-4097ef73de6b

[Profile] 프로필 정보 & 상품목록 & 팔로우

---

src/components/Login/LoginForm.jsx

LocalStorage에 set을 해야하는데 get을 해서 오류 수정했습니다.

[Login] localStorage 오류 수정

---

src/components/Modal/BottomSheetContent.jsx
src/components/Modal/BottomSheetModal.jsx
src/components/Modal/ConfirmModal.jsx
src/components/Post/PostCard.jsx
src/pages/HomePage.jsx

홈 피드 게시글 신고 기능 구현 반영
- 홈 피드에 뜨는 팔로우 한 유저의 게시글을 신고할 수 있는 기능 구현

[Feed] 홈 피드 게시글 신고 기능

---

src/components/Header/Header.jsx
src/components/NavBar/NavBar.jsx
src/components/Post/PostCard.jsx

Post UI 추가 구현 사항 반영
- 이미지 캐로셀 구현
- UserInfo 컴포넌트 활용, 프로필 페이지 내에선 안 보이도록 조건부 렌더링
이미지에 따라서 렌더링이 조금 느린 경우가 있어 이 부분은 수정할 계획입니다.

[Post] Post UI 추가 구현

---

src/components/Post/PostCard.jsx
src/pages/HomePage.jsx

매개변수 이름 변경 반영
- 매개변수를 data에서 post로 직관적으로 변경 후 이를 반영
- 신고 기능의 경우 비동기 통신 결과를 변수로 담아둘 필요 없어 이를 삭제함

[Post] 매개변수 이름 변경

---

src/components/Post/PostCard.jsx

merge 오류 수정 반영
- [앞선 PR](https://github.com/FRONTENDSCHOOL5/final-01-focal/pull/37)에서 merge conflict를 해결해 merge하였으나 겹치는 코드가 있어 이를 수정하였습니다.

[Post] merge 오류 수정

---

src/App.js
src/components/Splash/Splash.jsx

Splash 화면 구현
styled component의 keyframes를 사용하여  animation효과를 주었고,
App.js에서 useEffect를 사용하여 처음 마운트 되었을 때만 splash화면이 나타나도록 기능을 구현했습니다.
splash화면은 1.8초 후에 사라질 수 있도록 setTimeout을 통해 구현했습니다.
화면 디자인의 경우 추후 변경 될 수도 있을 것 같아요.
- 새로고침을 했을 때 splash화면이 보입니다.

[Splash] Splash 화면 구현

---

src/components/Input/RadioInput.jsx
src/components/Product/ImageUpload.jsx
src/components/Product/ProductUpload.jsx

ProductUpload.jsx 수정
input 폴더에 Radioinput.jsx 추가
원래 url을 썼던 input을 
radio type을 사용해 체크박스 형태로 상폼종류를 고르게 변경했습니다.

[Product] 상품등록 input type변경 & 이미지 업로드 수정

---

src/pages/PostPage.jsx

PostPage.jsx 기능구현
- 게시글 상세페이지로 불러오기
- 본인 작성 글엔 수정 삭제 바텀시트, 모달 구현
- 상대방 글엔 신고 바텀시트, 모달 구현
- 신고 기능 구현

[Post Detail] 상세페이지 조건부 모달,바텀시트 신고기능 구현

---

src/components/Post/PostUpload.jsx
src/pages/PostEditPage.jsx
src/pages/PostUploadPage.jsx

- 글 수정 페이지에서 버그 수정했습니다.
- 게시글 수정시 글만 수정 해서 올리고 싶은데 사진을 한장 꼭 골라야 글 수정이 가능하다는 버그가 있었음.
- 자신이 찍은 필름카메라 사진에 대해 적는 사이트이기 때문에 사진을 올려야하는 것이 필수라 사진 input에 required를 준 것이 원인이었음. (글만 수정한 경우 사진 input에는 아무것도 없는 상태이기 때문에 에러가 남)
- input에 required를 주는 것이 아닌, 글 업로드 버튼을 눌렀을 때 상태(state)의 length를 확인함으로써 버그를 해결함

[Post] 글 수정 페이지 버그 수정

---

src/components/Profile/MyInfoBtns.jsx
src/components/Profile/ProfileInfo.jsx
src/components/UserItem/UserFollowListItem.jsx
src/components/UserItem/UserInfo.jsx
src/pages/FollowersPage.jsx
src/pages/FollowingsPage.jsx

- 팔로워 팔로잉 페이지 기능 구현
- 페이지에 팔로우 리스트 뜨도록 구현
- 팔로우 페이지 내 취소 / 팔로우 구현
https://github.com/FRONTENDSCHOOL5/final-01-focal/assets/78803088/982c285e-f6cb-443a-a9c5-fc9c669b4597

[follow] 팔로잉 팔로워 페이지 기능 구현

---

src/pages/PostPage.jsx

PostPage.jsx
상세 페이지에서 본인글을 수정하고 삭제하는 기능을 구현했습니다.
https://github.com/FRONTENDSCHOOL5/final-01-focal/assets/117337499/d2105095-f9a8-4fb2-90b0-b189b5f9d69e

[Post Detail]  모달, 수정 삭제 기능 구현

---

src/api/instance/authInstance.js
src/assets/icons/icon-multiple.svg
src/components/Modal/BottomSheetModal.jsx
src/components/Profile/PostGalleryItem.jsx
src/components/Profile/ProductItem.jsx
src/components/Profile/ProfileInfo.jsx
src/components/Profile/ProfilePosts.jsx
src/components/Profile/ProfileProducts.jsx
src/pages/MyProfilePage.jsx
src/pages/UserProfilePage.jsx

- 프로필 페이지 피드 구현
- BottomSheet 적용
- 프로필 페이지 피드 기능 구현
- Bottomsheet 적용 후 기능 적용
https://github.com/FRONTENDSCHOOL5/final-01-focal/assets/78803088/a3b69385-4654-4c33-864c-4ea34d6128f5

[Profile] 바텀시트 적용 & 프로필 페이지 피드 기능 구현

---

src/components/Profile/ProfileInfo.jsx

[Profile] git 꼬임 해결

---

src/components/Input/TextInputBox.jsx
src/components/Post/PostComment.jsx
src/pages/PostPage.jsx

-TextInputBox.jsx
-PostComment.jsx
-PostPage.jsx
코드작성
-TextInputBox.jsx 게시버튼 기능구현,입력시 사용자 프로필 이미지 구현,자동완성 없애기
-PostComment 달린 댓글 시각 추적 로직구현, 댓글 기능구현
-PostPage 댓글 불러오기 api 통신 기능, 댓글 작성 api 통신기능, 오래된 순서대로 댓글정렬 로직 구현
댓글이 없을땐 댓글이 안 보이는 조건부 렌더링 구현
https://github.com/FRONTENDSCHOOL5/final-01-focal/assets/117337499/52b7c25b-421a-47d8-8798-8361124c2ac4

[Post Comments]댓글 기능 구현

---

src/Globalstyled.jsx
src/components/Input/RadioInput.jsx
src/components/Input/TextInput.jsx
src/components/Product/ImageUpload.jsx
src/components/Product/ProductCard.jsx
src/components/Product/ProductUpload.jsx
src/components/Profile/ProductItem.jsx
src/components/Profile/ProfileProducts.jsx
src/pages/HomePage.jsx
src/pages/ProductEditPage.jsx
src/pages/ProductUploadPage.jsx
src/routes/Router.jsx

상품 상세 모달 구현과 삭제, 수정 기능 구현을 반영하기 위한 PR입니다
- 상품 상세 페이지 역할을 하는 모달 UI를 구현하였습니다.
- 현재 사용자의 상품 상세 페이지라면 삭제와 수정 버튼을, 다른 사용자의 페이지라면 채팅 버튼을 놓고 해당 기능을 구현했습니다. 
- 상품 수정 기능을 추가하며 관련해 상품 등록 기능을 하는 코드를 분리했습니다.
- 불필요한 Fragment 등을 삭제해 콘솔에 뜨는 오류를 해결했습니다.
채팅 기능은 향후 채팅하고자 하는 유저의 정보가 헤더에 뜨도록 구현하는 등 실제 기능에 가깝게 수정할 계획입니다.

[product] 상품 상세 모달 및 삭제, 수정 기능 구현

---

src/components/Profile/PostGalleryItem.jsx
src/components/Profile/ProfileInfo.jsx
src/components/Profile/ProfilePosts.jsx
src/components/Profile/ProfileProducts.jsx
src/components/Profile/UserInfoBtns.jsx
src/pages/MyProfilePage.jsx
src/pages/UserProfilePage.jsx

- 프로필 전체적 수정
- Validation Check
- 프로필 UI 모바일 뷰에도 맞춰 수정
- 프로필 피드 갤러리 뷰일 시 이동 수정
- 프로필 Validation Check
validation check 시 postCard, Navbar 부분은 겹칠까봐 일단 제외하고 수정하였습니다.
스크롤바 띄어져서 보이는 부분은 다른페이지에서도 저렇게 뜨고, 브라우저 차이인 듯 합니다
https://github.com/FRONTENDSCHOOL5/final-01-focal/assets/78803088/13120982-0817-40fe-aa89-aad8ef6d09ef
https://github.com/FRONTENDSCHOOL5/final-01-focal/assets/78803088/080d67da-c905-47bf-99b0-d6a459cc99a4

[Profile] Profile 전체적 수정 및 Validation

---

src/components/Post/PostComment.jsx
src/pages/PostPage.jsx

PostPage.jsx
PostComment.jsx
코드작성
-불필요한 상태를 삭제하고, 댓글 작성에 따른 카운팅을 반영하게 했습니다.
-원래 있던 댓글 불러오기 댓글 입력 기능에서 본인 댓글이면 삭제가 
다른 사용자 댓글이면 신고가 뜨는 바텀시트,모달 기능을 구현했습니다.
-그에 따른 신고기능, 댓글 삭제 기능을 구현했습니다.
https://github.com/FRONTENDSCHOOL5/final-01-focal/assets/117337499/4c8a1e0b-5754-4ec9-b774-8a97c1d36e0e

[Post Comments]수정,삭제 기능 구현

---

src/pages/HomePage.jsx

HomePage 스크롤 위치 및 디자인 수정
HomePage에 main 요소에 height와 overflow 속성을 부여하여 스크롤이 main요소 안에서 움직일 수 있도록 코드를 작성했습니다.
또한 로딩 상태일 때와 팔로우한 사람의 글이 없을 때는 flex를 사용하여 컨텐츠가 가운데에 오도록 했습니다.
- 지금은 로딩중일 때 로딩중이라는 글씨를 보여주지만 추후 로딩 스피너를 추가할 예정입니다.

[Home] 스크롤 위치 및 디자인 수정

---

src/components/Profile/ProductItem.jsx
src/components/Profile/ProfileInfo.jsx
src/components/Profile/ProfilePosts.jsx
src/pages/FollowersPage.jsx
src/pages/FollowingsPage.jsx
src/pages/MyProfilePage.jsx
src/pages/UserProfilePage.jsx

- 프로필 페이지 수정 및 follow 0명 처리
- profile page scroll 수정
- profile page product 너비 지정
- follow page 0명일때 처리
- profile post없을때 코드 변경
https://github.com/FRONTENDSCHOOL5/final-01-focal/assets/78803088/326190fa-bd05-4f77-a24c-aef396089874

[Profile] 프로필 페이지 수정 및 follow 0명 처리

---

src/pages/MyProfilePage.jsx
src/pages/UserProfilePage.jsx

merge conflict 잘못 병합된 것 해결
프로필 페이지 merge conflict 잘못 병합된 것 해결했습니다.

[Merge] merge conflict 잘못 병합된 것 해결

---

src/pages/ChatListPage.jsx
src/pages/ChatRoomPage.jsx
src/pages/MyProfilePage.jsx

Page Header UI 수정
- ChatRoomPage Header ellipsis 버튼 추가
- ChatListPage NavBar 추가
- ChatListPage header text 추가

💄 Design: Page Header UI 수정

---

src/components/Post/PostComment.jsx
src/components/Profile/ProfilePosts.jsx
src/components/Profile/ProfileProducts.jsx
src/hooks/useModal.jsx
src/pages/HomePage.jsx
src/pages/MyProfilePage.jsx
src/pages/PostPage.jsx

useModal 커스텀훅 반영
- 중복되는 BottomSheet와 ConfirmModal을 여는 작업이 중복되어 useModal 커스텀훅을 생성해 이를 방지하고자 했습니다.

[Common] useModal 커스텀훅 구현

---

src/components/Chat/ChatItem.jsx
src/components/Chat/ChatList.jsx
src/components/Chat/ChatRoom.jsx
src/pages/ChatRoomPage.jsx

ChatRoomPage.jsx
ChatListPage.jsx
ChatRoom.jsx
ChatList.jsx
ChatItem.jsx
코드작성
-  채팅 리스트 링크 기능 구현
-  채팅방 나가기 바텀시트 및 모달 구현
-  특정 유저 외에 채팅 기록 없게 보이게 구현
-  채팅룸 헤더에 username 띄우기 구현
https://github.com/FRONTENDSCHOOL5/final-01-focal/assets/117337499/5a77b5c6-46ee-47b4-a4a2-28322f4670f8

[Chat] chat 기능구현

---

src/components/Header/Header.jsx
src/pages/HomePage.jsx

홈 화면 로고 클릭 시 맨 위로 가는 기능 반영
- 스크롤 문제로 게시글 부분과 헤더가 분리되면서 기존의 코드로는 로고를 눌러도 스크롤이 맨 위로 움직이지 않아 이를 useRef를 활용해 처리하였습니다.

[Feed] 스크롤 위로 가기 기능 수정

---

public/index.html
src/components/Input/TextInputBox.jsx
src/components/Post/PostComment.jsx

PostComment.jsx
TextInputBox.jsx
코드 작성
- 댓글을 엔터로도 입력 가능하게 구현했습니다.
- 댓글 프로필 이미지나 유저 닉네임 클릭시 그 사용자 프로필 페이지로 이동하게 했습니다.
없음

[Post Comments]댓글 엔터처리,프로필 이동

---

src/components/Post/PostCard.jsx
src/components/Profile/ProfilePosts.jsx

PostCard Design 디자인 수정 및 코드 리팩토링
- PostCard 3줄이상일 때 말줄임표 추가
- 전체적인 margin, padding, width 등 수정
- 버튼에 접근 가능한 이름 추가

[Post] PostCard Design 디자인 수정 및 코드 리팩토링

---

src/components/Post/PostCard.jsx
src/components/Post/PostComment.jsx
src/utils/convertTime.js

작성 시간 변환 함수 utils로 추출 및 재사용 반영
comment에 사용되었던 작성 날짜를 n일 전 등으로 표시하는 함수를 utils로 추출해 postcard에서 재사용하였습니다.
merge conflict가 발생 이를 처리한 후 다시 push하였습니다.

[Post] postcard 작성 시간 변환 

---

src/Globalstyled.jsx
src/components/Chat/ChatList.jsx
src/components/Chat/ChatRoom.jsx
src/components/Input/RadioInput.jsx
src/components/Input/TextInputBox.jsx
src/pages/ProductEditPage.jsx
src/pages/ProductUploadPage.jsx

- 전체적인 코드 접근성 고려 수정
- 접근성 고려 Heading tag 추가 alt 입력
- radio input margin값 수정
- 남아있던 console.log 제거
- Globalstyled overflow:none 추가

[Validation] 접근성 고려, 콘솔정리

---

src/components/Input/ProfileImageUploader.jsx
src/components/Post/PostCard.jsx
src/components/Post/PostUpload.jsx
src/components/UserItem/UserInfo.jsx
src/pages/HomePage.jsx
src/pages/PostPage.jsx
src/routes/Router.jsx
src/states/PathState.js

- 전체적인 코드 리팩토링
- 홈 디자인 수정
- router 경로수정
- 접근성, 마크업 오류 수정
- UserInfo 비즈니스 로직 변경

[Validation] 마크업 validation 및 접근성 고려

---

src/components/Loading/Loading.jsx
src/components/Profile/ProfilePosts.jsx
src/components/Profile/ProfileProducts.jsx
src/pages/FollowersPage.jsx
src/pages/FollowingsPage.jsx
src/pages/HomePage.jsx
src/pages/MyProfilePage.jsx
src/pages/UserProfilePage.jsx

로딩 스피너 적용
- Homepage, MyProfilePage, UserProfilePage, FollowersPage, FollowingsPage 로딩 스피너 적용
- merge conflict 해결

[Common] 로딩 스피너 적용

---

src/components/Header/Header.jsx

Header 접근성 관련 수정
Header 아이콘 버튼에 접근할 수 있는 이름을 추가하여 접근성 향상에 힘썼다.

[Header] Header 접근성 관련 수정

---

src/Globalstyled.jsx

스크롤 오류 수정
스크롤 오류 고쳤다고 생각했는데 안고쳐져있어서 root에 overflow: hidden을 주어 고쳤습니다.

[Page] 스크롤 오류 수정

---

src/components/NavBar/NavBar.jsx
src/components/NavBar/NavBarItem.jsx

- navbar 오류 수정
- navbar validation 체크 후 svg 컴포넌트 관련한 오류가 있어 이를 수정했습니다.

[Common] navbar 오류 수정

---

src/components/Modal/BottomSheetModal.jsx

bottom sheet 애니메이션 추가
- 게시글 등 bottomsheet이 올라올 때 자연스럽게 올라오도록 애니메이션 구현

[Common] bottomSheet 애니메이션 추가

---

src/utils/convertTime.js

convertTime.js
코드수정
조건 추가로 -1초전 까지 뜨던 문제 수정

[Post Comments]댓글기능 수정

---

src/pages/MyProfilePage.jsx
src/pages/UserProfilePage.jsx

- 프로필 페이지 반응형 시 전체 너비 변경
- 390 -> 380

[Profile] 반응형 시 너비 변경

---

src/api/apis/like.js
src/components/Common/PostCard/PostCard.jsx

좋아요 기능 API 분리 반영
api/apis/like.js 파일에 좋아요 및 좋아요 취소 api 통신 관련 코드 작성 후 이를 PostCard.jsx에 반영했으며 중복된 try catch문을 제거했습니다.

[API] 좋아요 기능 API 분리

---

src/api/apis/user.js
src/components/Common/ProfileForm/ProfileForm.jsx
src/components/Login/LoginForm.jsx
src/components/SignUp/SignUpForm.jsx
src/pages/ChatRoomPage.jsx
src/pages/MyProfilePage.jsx
src/pages/ProfileEditPage.jsx
src/pages/SearchPage.jsx
src/pages/SignUpPage.jsx

User 도메인 api 호출 코드를  분리
user 도메인 api 호출 코드를 분리하고 분리한 모듈을 코드에 적용하였습니다. 
- 로그인
- 회원가입
- 이메일 검증
- 계정 검증
- 유저 검색
- 내 정보 수정
- 내 정보 불러오기
위 7가지 api 호출 코드를 모듈화했습니다.

[API] user 도메인 api 분리

---

src/api/apis/image.js
src/components/Post/PostUpload.jsx
src/components/Product/ProductUpload.jsx
src/pages/ProfileEditPage.jsx
src/pages/SignUpPage.jsx

image도메인 api 분리 
image api 호출 코드를 분리를 하고 분리한 모듈을 코드에 적용했습니다.
- 한개의 이미지를 업로드하는 api인 /image/uploadfile
- 여러개의 이미지를 업로드하는 api인 /image/uploadfiles
두개의 api 호출코드를 모듈화했습니다

[API] image도메인 api 분리 

---

src/api/apis/post.js
src/components/Profile/ProfilePosts.jsx
src/pages/HomePage.jsx
src/pages/PostEditPage.jsx
src/pages/PostPage.jsx
src/pages/PostUploadPage.jsx

게시글 관련 기능 api 분리하고 이를 반영했습니다.
게시글 작성, 수정, 삭제, 신고 기능 api를 post.js에 분리하고 이를 관련 컴포넌트에 반영했습니다.

[API] 게시글 관련 api 분리

---

src/api/apis/product.js
src/components/Profile/ProfileProducts.jsx
src/pages/ProductEditPage.jsx
src/pages/ProductUploadPage.jsx
src/pages/SignUpPage.jsx

서버에 상품관련 요청 api를 파일분리해서 모듈화 했습니다.
상품 등록
상품 리스트
상품 삭제
상품 상세
상품 수정
api요청 코드를 분리했습니다.

[API] 상품 api 분리

---

src/api/apis/comment.js
src/components/Post/PostComment.jsx
src/pages/PostPage.jsx
src/pages/SignUpPage.jsx

서버에 댓글관련 요청 api를 파일분리해서 모듈화 했습니다.
댓글 리스트
댓글 작성
댓글 삭제
댓글 신고
api를 분리했습니다.

[API] 댓글 api 분리

---

src/components/Follow/FollowNone.jsx
src/pages/FollowersPage.jsx
src/pages/FollowingsPage.jsx

- 팔로우 페이지 구조변경
-  팔로우 리스트가 없을때를 컴포넌트로 따로 뺌 ( FollowNone )

[Follow] 팔로우 페이지 구조변경

---

src/components/Common/PostCard/PostCard.jsx

게시글 이미지 슬라이드 애니메이션 추가
게시글 이미지가 여러 장일 경우 나타나는 버튼에 aria-label 추가
게시글 이미지 슬라이드에 애니메이션을 추가를 위한 스타일링 변경 등의 작업을 진행했습니다.
게시글 이미지가 여러 장일 경우 생성되는 버튼에 접근성을 위한 aria-label을 추가했습니다.

[Post] 이미지 슬라이드 애니메이션, aria-label 추가

---

src/components/Profile/PostAlignButtons.jsx
src/components/Profile/PostNone.jsx
src/components/Profile/ProfilePosts.jsx

- 프로필 게시글 구조변경
- 프로필 게시글 삼항연산자 중첩 줄이기 위해
게시글 없을때를 컴포넌트로 따로 뺌 ( PostNone )
- 순수함수 만들기 위해 게시글 없음을 판독하도록 함수로 뺌
components > Profile 폴더 안의 컴포넌트들 명을 나름의 규칙으로..
프로필
- ProfileInfo
- MyInfoBtns
- UserInfoBtns
- ProfileProducts
- ProductItem 
- ProfilePosts
- PostGalleryItem
- PostAlignButton
- PostNone 
나눠 둔건데 알아보기 힘든거 같아 좋은 아이디어가 있으시다면 말씀부탁드려요..!

[Profile] 프로필 게시글 구조 변경

---

src/components/Chat/ChatRoom.jsx
src/components/Common/Input/TextInputBox.jsx
src/pages/ChatRoomPage.jsx

Chatroom.jsx
TextInputBox.jsx
ChatRoomPage.jsx
코드추가
전송 버튼을 누를시 리렌더링 되는 현상을 방지하고 채팅이 올라가는 기능을 구현했습니다.
https://github.com/FRONTENDSCHOOL5/final-01-focal/assets/117337499/19cb5299-719a-465a-a352-283d5a56f846

[Chat] input 리렌더링 방지, 전송기능 추가

---

src/layouts/NavBar/NavBar.jsx
src/layouts/NavBar/NavBarItem.jsx

Navbar  색상 변경 오류수정
- 기존 코드는 Navbar의 버튼을 눌러야 색상이 변하도록 되어있었기 때문에 로그아웃을 누르고 다시 로그인을 했을 때 Navbar 버튼 색이 프로필 버튼에 들어와있음을 볼 수 있음
- 기존 코드대신 밑의 코드로 변경함으로써, 해당 오류를 고칠 수 있었음
```
useEffect(() => {
if (
location.pathname === '/' ||
location.pathname === '/chat/' ||
location.pathname === '/profile/'
) {
setPathname(location.pathname);
}
}, []);
```
- 오류 고치기 전
- 오류 고친 후

[Common] Navbar 색상 변경 오류수정

---

src/api/apis/post.js
src/components/Post/PostsFeed.jsx
src/pages/HomePage.jsx

무한 스크롤 구현 및 컴포넌트 분리 반
원하는 범위의 데이터를 가져올 수 있도록 feedAPI를 업데이트 했습니다.
useRef와 IntersectionObserve를 활용해 스크롤이 현재 로딩된 포스트의 끝에 스크롤이 오는 것을 감지하면 새로운 데이터를 가져오는 무한 스크롤 기능을 구현했습니다.
PostsFeed 컴포넌트를 생성하여 데이터를 가져오고 무한 스크롤을 구현하는 로직을 분리했습니다.

[Feed] 무한 스크롤 기능 구현

---

src/components/Chat/ChatList.jsx
src/pages/ChatListPage.jsx
src/utils/getDate.js

채팅리스트 팔로잉 목록으로 뜨도록 구현
채팅 리스트 페이지에서 팔로잉 목록 불러오기 기능 구현
채팅 리스트 컴포넌트 Props를 통해 동적으로 변경
날짜 변형 함수 재사용 가능하도록 utils 폴더에 따로 생성

[Chat] 채팅리스트 목록수정

---

src/api/apis/follow.js
src/hooks/useScrollBottom.js
src/pages/FollowersPage.jsx
src/pages/FollowingsPage.jsx

- follow 페이지 무한스크롤 구현
- useScrollBottom 커스텀 훅을 생성하여 ref로 스크롤 되는 요소를 감지하여 스크롤 되는 요소가 화면의 하단에 접근하면 follow 페이지에서 다음 api 요청
- lodash를 이용하여 throttle을 적용하여, 스크롤 이벤트에 딜레이를 부여함으로써, 스크롤 동작 중에 여러 번의 호출을 제어
https://github.com/FRONTENDSCHOOL5/final-01-focal/assets/78803088/2c6ee110-2272-4e17-be61-8509a36aeb74

[Follow] follow 페이지 무한스크롤 구현

---

src/api/apis/post.js
src/components/Profile/ProfilePosts.jsx
src/pages/MyProfilePage.jsx
src/pages/UserProfilePage.jsx

- profile 의 post 무한스크롤 구현
- follow 브랜치에서 작업한 useScrollBottom을 이용하여 profile의 post 무한스크롤 구현
- follow 브랜치 머지하면 작동 될 것으로 보임
https://github.com/FRONTENDSCHOOL5/final-01-focal/assets/78803088/267a9a3d-7fa5-4baf-8abc-269e7cbdf0a1

[Profile] 프로필 페이지의 게시글 무한스크롤 구현

---

src/components/Post/PostsFeed.jsx
src/pages/HomePage.jsx
src/states/PathState.js

postsFeed 리펙터링 및 디자인 문제 해결
postsFeed의 변수, 함수명 및 조건 리펙터링
feed에 postDatas가 없는 경우 콘텐츠가 가운데 오도록 스타일 조정

[Feed] postsFeed 리펙터링 및 디자인 문제 해결
